version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=foobar123
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=foobar123
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db-data:
